### ISSUE TITLE
[Feature Request] Capitalize letters in the Options/Controls for better look and consistency.

### ISSUE THREAD

**Issue by RDKRACZ** [TomB-134/MinimalMenu#15]
When there is a key name it is capitalized so single-letter key names should be too.
![shouldnt these be capitalised](https://user-images.githubusercontent.com/43277609/110123278-03274f00-7dc1-11eb-9e88-5882ea651f16.png)

![image](https://user-images.githubusercontent.com/43277609/110125806-04a64680-7dc4-11eb-9f7c-0796672be730.png)

**Comment by TomB-134** [comment]
I feel like this would lead to confusion.
