### ISSUE TITLE
Incompatibility with 'Slight' GUI Modifications

### ISSUE THREAD

**Issue by srnyx** [TomB-134/MinimalMenu#18]
Game crashes on startup when using 'Slight' GUI Modifications and MinimalMenu together
Crash report: https://pastebin.com/H5ih40xD

**Comment by shedaniel** [comment]
https://github.com/TomB-134/MinimalMenu/blob/f46aa7c23be059d25f8580a28341e64e5f2d5f41/src/main/java/minimalmenu/mixin/TitleScreenMixin.java#L59

**Comment by TomB-134** [comment]
Not designed to work together, one or the other.
