### ISSUE TITLE
[Feature Request] Remove version text + Center title screen

### ISSUE THREAD

**Issue by MudkipBanana** [TomB-134/MinimalMenu#27]
I really like this mod, but the only gripe I have about it is that it doesn't remove the version text:
![image](https://user-images.githubusercontent.com/42680119/121814862-3ccde880-cc41-11eb-98cc-714ca6b29786.png)
Also, it would be really nice to have an option to center the title screen (move the title and buttons around with an x/y offset)
![image](https://user-images.githubusercontent.com/42680119/121814866-43f4f680-cc41-11eb-9079-85051aeeaf3c.png)

**Comment by RDKRACZ** [comment]
[Off topic] May I ask how and where did you get this panorama?

**Comment by MudkipBanana** [comment]
[Off topic] https://www.curseforge.com/minecraft/texture-packs/darkui

**Comment by TomB-134** [comment]
I'll look into the version text removal. "move the title and buttons around with an x/y offset" This already exists or am I missing something? Just go into the title screen options and there should be an xy offset there for you.
