### ISSUE TITLE
[Feature Request] Lock Multiplayer view

### ISSUE THREAD

**Issue by puggan** [TomB-134/MinimalMenu#29]
To prevent the Kids from removing or editing the server-row, the ability to remove "Add Server", "Edit", "Delete", and "Direct connect".
This with #5 would allow us to only have the "Multiplayer" option on the first menu, and then only have the one server that we playing on available.

**Comment by TomB-134** [comment]
I do like this idea, although I think maybe password protecting worlds and servers could be an entirely separate mod since it has such broad uses. 

I can probably implement a option to remove everything but the play button, and have that option locked behind a pin code of some sort. Thoughts?
