### ISSUE TITLE
full ru translate MinimalMenu. thanks your amazing mod

### ISSUE THREAD

**Issue by Shelbikk** [TomB-134/MinimalMenu#37]
[minimalmenu-1.18.1-0.1.0.zip](https://github.com/TomB-134/MinimalMenu/files/7740180/minimalmenu-1.18.1-0.1.0.zip)

**Comment by TomB-134** [comment]
Hey thank you! I've added your file. Since you made this a few new translations have been added, so if you have time feel free to open a pull request with the updated translation :P
