### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by RaptaG** [TomB-134/MinimalMenu#40]
On 1.18.2 the game crashes with the latest version of Minimal Menu.. Could you upgrade it to 1.18.2?

**Comment by somebirby** [comment]
That would be great. This mod makes my experience so much better

**Comment by kxkxrxtx** [comment]
Yes, please!

**Comment by RaptaG** [comment]
> Yes, please!

Please, **don't** make comments if you like the idea, just react with :+1: on my original comment, so that the people interested will only be notified when the dev responds. Thanks a lot, have a nice day!

**Comment by yesn0t** [comment]
headsup : MinimalMenu v0.1.5 for minecraft 1.18.2 : ([curseforge only](https://www.curseforge.com/minecraft/mc-mods/minimal-menu/files/3798011) at the moment)

**Comment by ST-DDT** [comment]
Works like a charm 👍

**Comment by RaptaG** [comment]
> headsup : MinimalMenu v0.1.5 for minecraft 1.18.2 : ([curseforge only](https://www.curseforge.com/minecraft/mc-mods/minimal-menu/files/3798011) at the moment)

Cool!. It's about time that I close this issue
