### ISSUE TITLE
Bug/Feature Request: Player Reporting button

### ISSUE THREAD

**Issue by chitinlink** [TomB-134/MinimalMenu#46]
In 1.19.2, the new Player Reporting button looks like this with the mod:
![image](https://user-images.githubusercontent.com/52284719/185581368-c73cec9a-2c82-4d8d-9cb8-f6414fb2a923.png)
![image](https://user-images.githubusercontent.com/52284719/185581744-b83d0088-43a3-4299-838e-a4c60a87eefe.png)

So obviously that's a bug, but it would also be nice to be able to toggle the button as well.

See also: https://modrinth.com/mod/nrb

**Comment by t3rminus** [comment]
I'm having this issue as well. It's very weird.

**Comment by TomB-134** [comment]
When I get around to supporting 1.19.2, should be soon.
