### ISSUE TITLE
Mark 0.1.5 as compatible with 1.19.2 on curseforge

### ISSUE THREAD

**Issue by ST-DDT** [TomB-134/MinimalMenu#47]
I use a modloader/updater that shows me whether my mods are up to date (and compatible).
It shows that minimal menu is not compatible with 1.19.2 because it isn't listed as supported version in curseforge:

https://www.curseforge.com/minecraft/mc-mods/minimal-menu/files/3826009

Please add 1.19.2 as supported Game Version to your file.

**Comment by TomB-134** [comment]
I don't believe the mod is currently compatible with 1.19.2. Hence why it isn't supported. Soon though.

**Comment by ST-DDT** [comment]
It appears to be working fine to me:
![grafik](https://user-images.githubusercontent.com/1579362/193398928-3de42e58-036d-49d0-a4c1-541df43a92c5.png)

Is there anything that isn't working?
(I'm using Fabric)

**Comment by keatit71** [comment]
I think when they mean its not compatible with 1.19.2 they haven't implemented ways to hide the report button from the pause menu and other new buttons added in 1.19.1-1.19.2
