### ISSUE TITLE
[Feature Request] Hide Mods menu item

### ISSUE THREAD

**Issue by braxtonhall** [TomB-134/MinimalMenu#5]
Hello I really like this mod! A lot!

The only thing that would make this better is if the `Mods` menu item could be hidden from the main menu.
For some users, this would mean that `Mods` would be accessed under `Options...`.

Or, for other users, it might even be preferred to hide `Mods` _entirely_ if they are comfortable editing the `config/minimalmenu.json`, though I assume this would require a warning.

**Comment by puggan** [comment]
Hiding the `Mods` menu completely maybe shouldn't have a GUI option, and only be avaible from the config-json,
so people don't exidently lock them self out.

**Comment by braxtonhall** [comment]
Oh! Was this feature implemented? Or is it a `wontfix`?
